In [1]:
import pandas as pd;import numpy as np

In [3]:
df = pd.DataFrame({"boy":[175, 177, 178, 181, 182, 183, 184, 189, 190],
                  "deneyim":[4, 6, 3, 2, 6, 3, 7, 2, 6],
                  "maas":[12, 18, 15, 16, 24, 20, 28, 24, 32]})

In [4]:
df

boy  deneyim  maas
0  175        4    12
1  177        6    18
2  178        3    15
3  181        2    16
4  182        6    24
5  183        3    20
6  184        7    28
7  189        2    24
8  190        6    32

In [5]:
df.maas.mean()

21.0

In [9]:
df.maas - df.maas.mean()

0    -9.0
1    -3.0
2    -6.0
3    -5.0
4     3.0
5    -1.0
6     7.0
7     3.0
8    11.0
Name: maas, dtype: float64

# Mean Model

In [32]:
# Toplam Model Erroru
(df.maas-df.maas.mean()).pow(2).sum()

340.0

# İlk Model

In [13]:
filt = (df.boy <= 180)
filt

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
Name: boy, dtype: bool

In [19]:
# 180 cm den Kısa Olanlar
df1 = df[filt]
df1

boy  deneyim  maas
0  175        4    12
1  177        6    18
2  178        3    15

In [18]:
# 180 cm den Uzun Olanlar
df2 = df[~filt]
df2

boy  deneyim  maas
3  181        2    16
4  182        6    24
5  183        3    20
6  184        7    28
7  189        2    24
8  190        6    32

In [22]:
df1.maas.mean()

15.0

In [23]:
df2.maas.mean()

24.0

# İlk Bölme: Error

In [40]:
(df1.maas - df1.maas.mean()).pow(2).sum()+(df2.maas - df2.maas.mean()).pow(2).sum()

178.0

# İkinci Bölme

In [29]:
filt = (df2.boy <185)
filt

3     True
4     True
5     True
6     True
7    False
8    False
Name: boy, dtype: bool

In [34]:
df3 = df2[filt]

In [35]:
df4 = df2[~filt]

In [36]:
df3

boy  deneyim  maas
3  181        2    16
4  182        6    24
5  183        3    20
6  184        7    28

In [37]:
df4

boy  deneyim  maas
7  189        2    24
8  190        6    32

# İkinci Bölme: Error

In [41]:
(df1.maas - df1.maas.mean()).pow(2).sum()+(df3.maas - df3.maas.mean()).pow(2).sum()+(df4.maas - df4.maas.mean()).pow(2).sum()

130.0

# Üçüncü Bölme

In [42]:
filt = (df3.deneyim<=5)

In [46]:
df5 = df3[filt]
df5

boy  deneyim  maas
3  181        2    16
5  183        3    20

In [47]:
df6 = df3[~filt]
df6

boy  deneyim  maas
4  182        6    24
6  184        7    28

In [48]:
df5.maas.mean()

18.0

In [49]:
df6.maas.mean()

26.0

# Üçüncü Bölme: Error

In [50]:
(df1.maas - df1.maas.mean()).pow(2).sum()+(df4.maas - df4.maas.mean()).pow(2).sum()+(df5.maas - df5.maas.mean()).pow(2).sum()+(df6.maas - df6.maas.mean()).pow(2).sum()

66.0

In [4]:
np.linspace(10, 100, 19, dtype="int")

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [6]:
np.linspace(0, 1000, 26, dtype="int")

array([   0,   40,   80,  120,  160,  200,  240,  280,  320,  360,  400,
        440,  480,  520,  560,  600,  640,  680,  720,  760,  800,  840,
        880,  920,  960, 1000])

In [5]:
np.arange(10,101, 5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [8]:
np.zeros((3,5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [11]:
np.zeros((2,6), dtype="int")

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [12]:
np.random.random((3,5))

array([[0.17594481, 0.78370583, 0.25816119, 0.73171824, 0.38153986],
       [0.09612049, 0.71373818, 0.7507616 , 0.5433748 , 0.61714807],
       [0.22349605, 0.42855075, 0.63095539, 0.56402897, 0.07581746]])

In [13]:
np.random.randint(10, 30, (4,5))

array([[14, 24, 24, 24, 22],
       [26, 26, 26, 16, 15],
       [25, 16, 22, 25, 25],
       [14, 23, 20, 18, 26]])

In [14]:
np.random.randint(0, 50, (4,6))

array([[38, 33, 28, 46, 31, 26],
       [25, 48,  7, 13, 11, 13],
       [15,  3,  2, 36, 11, 29],
       [30, 48, 15,  2, 36, 34]])

In [17]:
sr = np.arange(-30,11)


In [18]:
sr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10])

In [19]:
sr[5:19]

array([-25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13,
       -12])

In [23]:
res = np.arange(60).reshape(3,5,-1)

In [24]:
res.ndim


3

In [25]:
res.shape

(3, 5, 4)

In [26]:
arr2d = np.arange(40).reshape(8,5)

In [27]:
arr2d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [28]:
arr2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [31]:
arr3d = np.arange(60).reshape(3, 5, -1)


In [33]:
for x in np.nditer(arr3d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
